/texts:
get:
  description: Returns all texts from the system.
  responses:
    '200':
      description: A list of texts.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/text'

get:
  description: Returns texts based on ID
  summary: Find text by ID
  operationId: getTextById
  responses:
    '200':
      description: text response
      content:
        '*/*' :
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Text'
    default:
      description: error payload
      content:
        'text/html':
          schema:
            $ref: '#/components/schemas/ErrorModel'
parameters:
- name: id
  in: path
  description: ID of text to use
  required: true
  schema:
    type: array
    items:
      type: string 
  style: simple