name: continuos-integration

on:
  push:
    branch: [ main, dev ]
  pull_request:
    branch: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: testing

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,W503,W504 core setup
      - name: Coverage report
        env:
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          coverage run manage.py test
          coverage report -m